version: '3'
services:
  grafana_graphite:
    build: .
    image: kamon/grafana_graphite
    restart: always
    container_name: kamon-grafana-dashboard
    ports:
      - '80:80'
      - '81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - ${GRAFANA_GRAPHITE_VAR_DIR}/data/whisper:/opt/graphite/storage/whisper
      - ${GRAFANA_GRAPHITE_VAR_DIR}/data/grafana:/opt/grafana/data
      - ${GRAFANA_GRAPHITE_VAR_DIR}/log/graphite:/opt/graphite/storage/log
      - ${GRAFANA_GRAPHITE_VAR_DIR}/log/supervisor:/var/log/supervisor